### ISSUE TITLE
Declare / display IATI version found in files

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#52]
Via the overnight script pull out the ``version=""`` attribute of the ``iati-activities`` or ``iati-organisation`` element for each file

Publish this in the record metadata - eg: http://iatiregistry.org/dataset/dfid-af

----------
Only display the version, if it meets one of these values: http://iatistandard.org/codelists/Version/
If a version is not found, or not on this code list, then display ``n/a``

----------
NB: we could also look to a search term on http://iatiregistry.org/dataset - but the issue remains that not all values will be on the Version codelist - one to discuss

**Comment by amercader** [comment]
Done, yes n/a appears if there is an invalid version.

http://iati2.staging.ckanhosted.com/dataset/aa-organisation

**Comment by stevieflow** [comment]
Great, thanks
