### ISSUE TITLE
Change link for preview of package

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#53]
Change the URL to preview a package from:

http://tools.aidinfolabs.org/showmydata/index.php?url=[file URL]

to

http://preview.iatistandard.org/index.php?url=[file URL]

**Comment by Mattdevinit** [comment]
@brew - I think these links to new previewer were part of the IATI Registry staging site, but they haven't gone live, could you check it out and push to live please?

**Comment by brew** [comment]
The `iati.preview_service` setting in the config needed to be changed to the correct url. That's been done now.

**Comment by Mattdevinit** [comment]
great - thanks @brew
