### ISSUE TITLE
Rename date update field labels

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#57]
On a publisher / search page, eg:

http://iatiregistry.org/publisher/minbuza_nl
http://iatiregistry.org/dataset

Change "Last modified" to "IATI data updated"

-----
On a package listing page

http://iatiregistry.org/dataset/minbuza_nl-activities

Data updated > IATI data updated
Record updated > IATI registry updated

**Comment by stevieflow** [comment]
any update on this?

**Comment by amercader** [comment]
Done

http://iatiregistry.org/dataset/minbuza_nl-activities
http://iatiregistry.org/publisher/minbuza_nl

**Comment by stevieflow** [comment]
Excellent, thanks
