### ISSUE TITLE
Update CSV help text

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#58]
In /help_csv-import - need to remove guidance on the fields that have been removed in #51 and #50 

@amercader I could do this via a PR from the IATI fork (or it might be easier for you to just do)?

**Comment by amercader** [comment]
Done http://iati2.staging.ckanhosted.com/help_csv-import

**Comment by stevieflow** [comment]
Thanks

I wonder if we should remove:

> <table><tbody><tr><td>default-language</td><td>Legacy field - not required</td></tr></tbody></table>

**Comment by amercader** [comment]
Done
