### ISSUE TITLE
Advert box for IATI Datastore

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#59]
Data search page: http://iatiregistry.org/dataset
Publisher page: http://iatiregistry.org/publisher
Using IATI data: http://iatiregistry.org/using-iati-data
About: http://iatiregistry.org/about

Add a new box to the right hand side navigation - where we can advertise and direct people to the IATI datastore

Will include a small graphic and text - to follow

**Comment by amercader** [comment]
Done

http://iati2.staging.ckanhosted.com/dataset
http://iati2.staging.ckanhosted.com/using-iati-data

Let me know if you want to change the text or icon (can be any of [these](http://fortawesome.github.io/Font-Awesome/3.2.1/icons/))

**Comment by stevieflow** [comment]
That's great - thanks
