### ISSUE TITLE
Provide link to dashboard

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#63]
On an publisher page - eg:

http://iatiregistry.org/publisher/dipr

.. it would be useful to include a link through to their page on the IATI dashboard.  In the above case, this would be:

http://dashboard.iatistandard.org/publisher/dipr.html

Therefore, on the Registry - on the right hand side, could we have a new menu item (below "Data issues") for Dasboard - with a link constructed (http://dashboard.iatistandard.org/publisher/[Publisher_RegistryID].html

**Comment by amercader** [comment]
Done.

I've added the link to the publisher box under the logo, as it is where it belongs conceptually rather than below the search filters, but happy to change it.

The icon can be any of [these](http://fortawesome.github.io/Font-Awesome/3.2.1/icons/).

**Comment by stevieflow** [comment]
Excellent, thankyou
