### ISSUE TITLE
Publisher > About - data portal/user interface link

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#64]
In the publisher profile, there is a question for a user interface (last one):

http://iatiregistry.org/publisher/about/unhabitat

This is often a URL, which does not become an active link when published.  Either:

- 1 - make such links become active in this question
- 2 - we build another field for this, which can then be inserted into a more prominant   position on the Registry page for the publsher (eg, underneath the logo).  

Quite a few publishers have user interfaces now - but they are not evident
 
Option 2 would be preferable - but perhaps 1 can be addressed quickly...

**Comment by amercader** [comment]
I added a new field (option 2):

http://iati2.staging.ckanhosted.com/publisher/unops

For reference, these are the publishers that have a url on the UI field:

```
     name      |                                                           value                                                           
---------------+---------------------------------------------------------------------------------------------------------------------------
 bond          | www.bond.org.uk/openinformation
 dgpolde2      | http://www.maec.es/es/MenuPpal/CooperacionInternacional/EstadisticasAOD/Paginas/estadisticas_ayudaoficialdesarrollo.aspx 
 ec-echo       | https://webgate.ec.europa.eu/hac/ 
 livingearth12 | www.livingearth.org.uk
 manxtimes     | www.manxtimes.com/iati directory with xml files\r                                                                        +
               | 
 mrc           | http://www.mrc.ac.uk/Ourresearch/Globalhealth/Whatwedo/index.htm
 nrc           | http://www.nrc.no/?did=9670216
 pact          | www.pactworld.org/opendata
 raju_123      | http://iatistandard.org/organisation-standard/file-header/
 sida          | http://www.openaid.se
 unhabitat     | http://open.unhabitat.org/
 unops         | https://data.unops.org
 vizzuality    | http://ngoaidmap.org
 wvuk          | www.worldvision.org.uk/transparency
 zimmzimm      | www.openaidsearch.org
(15 rows)
```

The ones starting with www need http added to them.

**Comment by stevieflow** [comment]
That's great - thanks

I presume when we go live that the database will be copied across accordingly?

**Comment by amercader** [comment]
@stevieflow I haven't filled the new UI URL fields (except for that one example). I can do it automatically once we deploy to production (the stagind db is out of date)

**Comment by stevieflow** [comment]
@amercader great - thanks.  Had thought so.  We can do a review of the values and update once live (as we did with the logo, etc)

**Comment by stevieflow** [comment]
Hi @amercader please could you rename the text label for this link to "Publisher's data platform" ?

**Comment by amercader** [comment]
Done
