### ISSUE TITLE
Publisher > Add link to d-portal

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#68]
Similar to #63 , can we include a link from the publisher page to d-portal

Example:

http://d-portal.org/ctrack.html?publisher=41119

The 41119 value is found in the field "IATI Identifier" in the Registry publisher profile.

If value is blank, then do not include a link

**Comment by stevieflow** [comment]
See also: https://github.com/okfn/ckanext-iati/issues/69

**Comment by amercader** [comment]
Done, see #69
