### ISSUE TITLE
Publisher page > Info box

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#69]
Regarding the recent developments and issues to add links to dashboard / d-portal etc - could we please add:

- Publisher Registry ID (printed as Identifier: XYZ)
- Publisher HQ Country ((HQ Country: ABC)
- Link: Publisher website

Additionally, can we then collect into a *new* box on the right hand side of the publisher page, beneath the name/logo/info of the publisher - labelled "Publisher IATI data" -  the following:

- Link: IATI Dashboard 
- Link Publisher d-portal
- Link: Publish data portal (if exists)

**Comment by amercader** [comment]
Done see http://iati2.staging.ckanhosted.com/publisher/unops
