### ISSUE TITLE
Duplicate Dashboard pages

### ISSUE THREAD

**Issue by stevieflow** [okfn/ckanext-iati#70]
The page http://iatiregistry.org/dashboard is now text about the IATI Dashboard .. but not the IATI Registry Dashboard, which lists my packages and activity.

It would be useful to reinstate the Registry Dashboard at http://iatiregistry.org/dashboard, and position the IATI Dashboard content elsewhere

**Comment by Mattdevinit** [comment]
@brew please could we amend the 'Dashboard' link (there's two - in this case the one between 'sysadmin' and 'my account' when logged in on the Registry site) to be called 'My data' and have the user's packages/activity as described by @stevieflow there?
Then we can just keep the http://iatiregistry.org/dashboard page as it is, linking to IATI Dashboard

**Comment by brew** [comment]
This is fixed and deployed. The url for the registry dashboard is now `/registry-dashboard`.

**Comment by Mattdevinit** [comment]
great - thanks @brew
