### ISSUE TITLE
Deployment of recent pull request

### ISSUE THREAD

**Issue by dalepotter** [okfn/ckanext-iati#86]
Just a ticket to follow-up on the deployment of this pull request that we initially submitted the week before last: https://github.com/okfn/ckanext-iati/pull/83

The code has been submitted but this seems to be awaiting deployment to the current server: https://iatiregistry.org

Any chance you could follow this up @chrisviderum Many thanks!

**Comment by chrisviderum** [comment]
Good morning Dale!

I wasn't aware that something needs to be done so far. I will take care.

**Comment by polarp** [comment]
@dalepotter @chrisviderum FYI the pull request is deployed to https://iatiregistry.org.

**Comment by dalepotter** [comment]
@polarp @chrisviderum Many thanks for addressing this one so quickly! I will now close the issue...
