### ISSUE TITLE
Pull requests for merging and deployment

### ISSUE THREAD

**Issue by dalepotter** [okfn/ckanext-iati#89]
@chrisviderum just to flag that I added a couple new pull requests a couple days ago (https://github.com/okfn/ckanext-iati/pull/87 and https://github.com/okfn/ckanext-iati/pull/88), which seek to fix some links after a domain name for an external site changed.

Would it be ok to schedule a developer to take a look at these and deploy to the live/staging instances?

**Comment by chrisviderum** [comment]
@dalepotter thanks for notifying! I don't receive messages, when a new pull request was set. I have already scheduled it now. 

I will update here soon!

**Comment by chrisviderum** [comment]
@dalepotter I think those pull requests were accepted a week ago. 

Can we close this one?

**Comment by dalepotter** [comment]
Many thanks @chrisviderum - these have now been deployed, so I will close the issue.
